### PR TITLE
Added sticky property to group buttons closes #29

### LINKED ISSUE #29: Fix positioning of buttons in popup
Currently when there are too many tabs in the current window, we need to scroll down too much to reach out the button group. This is kinda anti UX.

Proposed solution could be provilding the button above the list or fix the button group position so that list scrolls below it.

### PR DESCRIPTION
**Pull request by Serjeel-Ranjan-911**
Also corrected some display properties in body.
Fixes #29

### CODE REVIEW

**Comment by daemon1024** [comment]
Thanks for the PR @Serjeel-Ranjan-911 

Can you attack a screenshot/screencast showing what the current popup looks like.

Also please edit the issue description and link your issue there. [Ref](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

**Comment by Serjeel-Ranjan-911** [comment]
https://user-images.githubusercontent.com/74287984/110108535-548c0a00-7dd2-11eb-950d-11f3dfdfb26f.mp4

Here is the screencast. @daemon1024 .

According to the reference. "Anyone with write permissions to a repository can manually link a pull request to an issue". Maybe I cannot do it.

**Comment by akshgpt7** [comment]
You just need to edit the PR description and add the issue number (eg. `closes #1`).
This will automatically close that issue when this PR is merged.

**Comment by daemon1024** [comment]
As well the thing you are quoting is for those who are not the author of PR, but here you are :D

**Comment by daemon1024** [comment]
@Serjeel-Ranjan-911 looks awesome, but I was wondering how would it look if the buttons would be sticking to the bottom. Can you do that too? Thank You.

**Comment by Serjeel-Ranjan-911** [comment]
> As well the thing you are quoting is for those who are not the author of PR, but here you are :D

will this work?

**Comment by Serjeel-Ranjan-911** [comment]
> @Serjeel-Ranjan-911 looks awesome, but I was wondering how would it look if the buttons would be sticking to the bottom. Can you do that too? Thank You.

yes can be done.

**Comment by daemon1024** [comment]
> will this work?

IMG_20210305_170042
There should be a edit button near your comment. Just do that add any keyword say `Fixes ` followed by `#1234` this will link your pull request to the particular issue.

**Comment by Serjeel-Ranjan-911** [comment]
> > @Serjeel-Ranjan-911 looks awesome, but I was wondering how would it look if the buttons would be sticking to the bottom. Can you do that too? Thank You.
> 
> yes can be done.


https://user-images.githubusercontent.com/74287984/110110745-4b506c80-7dd5-11eb-8675-f6f3d95d64f7.mp4

here is the preview when button sticks to bottom.

**Comment by daemon1024** [comment]
Looks great. Can you commit it? So we can proceed with merging the PR? 🙌

**Comment by Serjeel-Ranjan-911** [comment]
> Looks great. Can you commit it? So we can proceed with merging the PR? 🙌

ya sure.

**Review by daemon1024 — APPROVED** [review]
Great Work, Thank You for the PR. We are planning a new release soon so look forward to seeing this change in the release.

If you are using the extension, would be glad to have any kind of feedback on it. 🙌

**Comment by Serjeel-Ranjan-911** [comment]
> Great Work, Thank You for the PR. We are planning a new release soon so look forward to seeing this change in the release.
> 
> If you are using the extension, would be glad to have any kind of feedback on it. 🙌

Thank you. with this I did my first ever open source contribution.

**Comment by daemon1024** [comment]
That's great @Serjeel-Ranjan-911🎉, Glad to know that 😁

**Pull request merged**
