### PR TITLE
Filter out the TabuRei tab while collapsing

### LINKED ISSUE #20: Ignore the Tab Manager Tab while collapsing?
Currently, when the current set of tabs are collapsed, the tab manager tab is also saved.
I think that tab could be ignored while collapsing?

### PR DESCRIPTION
**Pull request by JRavi2**
Closes #20 
For now, I've just added another condition to the existing filter. But, let me know if I should create a new function, just in case if we require to validate the tabs anywhere else in the future.

### CODE REVIEW

**Comment by daemon1024** [comment]
@JRavi2 Refactoring it to a new function would make sense, since I am planning to use a persistent store for popup as well so that more features can be added, so it would be easier to call this out.

**Comment by JRavi2** [comment]
@daemon1024 Done :)

**Comment by daemon1024** [comment]
LGTM. Thank You.

**Review by daemon1024 — APPROVED** [review]

**Comment by daemon1024** [comment]
Hey @JRavi2, Sorry for pinging again but it seems like it is having conflicts after the recent merge. Can you please resolve it and update your PR? Thank You :)

**Comment by JRavi2** [comment]
@daemon1024 Conflicts resolved

**Comment by daemon1024** [comment]
Thank You @JRavi2, we are planning to release v1.0.0 soon look forward to it and feel free to work on any open issue or TODO in github project.

**Pull request merged**
